version: 2.1

workflows:
  tox_tests:
    jobs:
      - unit_tests:
          version: "3.6"
      - unit_tests:
          version: "3.7"
jobs:

  unit_tests:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install pipenv
            pipenv install --dev --ignore-pipfile
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
